### ISSUE TITLE
Cassandra schema.cql error

### ISSUE THREAD

**Issue by karthika-ab** [rdkcentral/xconfserver#21]
After running  Cassandra DB ,while creating  a  corresponding scheme using schema.cql file from xconf-angular-admin or xconf-dataservice module, it throws an error  ""**No keyspace has been specified. USE a keyspace, or explicitly specify keyspace.tablename**"".

To overcome the issue we have added the following highlighted line in schema.cql file:

> CREATE KEYSPACE IF NOT EXISTS demo WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
> **+USE demo;**
> CREATE TABLE "ApprovedChange" (key text,column1 text,value blob,PRIMARY KEY ((key), column1)) WITH COMPACT STORAGE;
>

**Comment by gdj-cmcst** [comment]
This will be addressed.

**Comment by gdj-cmcst** [comment]
This issue was addressed with this merge:

https://github.com/rdkcentral/xconfserver/commit/bfb490baed2beb67ac5dbf3d7635f7ed17082ef2
