### ISSUE TITLE
Exceptions observed in xconf-dataservice and xconf-angular-admin

### ISSUE THREAD

**Issue by karthika-ab** [rdkcentral/xconfserver#23]
We are observing the following exceptions in xconf-dataservice and xconf-angular-admin during mvn clean install

```
Running com.comcast.xconf.CompleteTestSuite
java.lang.instrument.IllegalClassFormatException: Error while instrumenting com/comcast/xconf/logupload/DeviceSettingsFieldAccess.
	at org.jacoco.agent.rt.internal_035b120.CoverageTransformer.transform(CoverageTransformer.java:93)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
.
.
.
.
java.lang.instrument.IllegalClassFormatException: Error while instrumenting com/comcast/xconf/logupload/LogUploadSettingsFieldAccess.
	at org.jacoco.agent.rt.internal_035b120.CoverageTransformer.transform(CoverageTransformer.java:93)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188) 

```
The complete error log is attached as [xconf-data-service-error.txt](https://github.com/rdkcentral/xconfserver/files/5807223/xconf-data-service-error.txt)
 and [xconf-angular-admin-error.txt](https://github.com/rdkcentral/xconfserver/files/5807229/xconf-angular-admin-error.txt)

**NOTE** : We are able to bring up the UI successfully despite the above exceptions although we are not sure of the side effects caused  by them.

**Comment by gdj-cmcst** [comment]
As noted from examination:

This error is due to the jacoco-maven-plugin and should not affect building operations. It was also observed that the expected result of using the plugin is not happening. It'll either be fixed or removed.
