### ISSUE TITLE
Import not working for DCM formulas if upload repository URL  with TFTP issue is linked with the formula

### ISSUE THREAD

**Issue by ajayan508** [rdkcentral/xconfserver#38]
Context : We are trying to migrate the data from an existing deployment of old xconfserver to the new xconfserver 

Related issue : https://github.com/rdkcentral/xconfserver/issues/25 

**Steps to reproduce**

1. Go to DCM ->  Upload repository
2. Click on 'Import' from the drop down menu next to 'Create' button.
3. Upload a json 'Upload repository' data exported from existing xconf server that has TFTP protocol and it's URL , say 192.168.0.103

Result : Error message 'Url is not valid' is displayed. As a result of this, DCM import formula also won't work. 

1. Go to DCM -> Formulas
2. Click on 'Import' from the drop down menu next to 'Create' button.
3. Upload a json 'Formulas' data exported from existing xconf server that has upload Urls that were not imported due to TFTP issue

Result :  As there were issues in upload repository, we are not expecting this step to pass for all formulas. A set of error messages are thrown stating that upload reposiitory Id is not present. 
		  
![image](https://user-images.githubusercontent.com/49313548/107973538-546eca80-6fdb-11eb-8586-d7042c6dc03f.png)

But the other formulas without any missing upload repository URL(due to tftp issue) is also not getting imported. The URls linked with those formulas are there  in 'Upload repository' and when we import also, no error is thrown related to those formulas. Errors are shown only for the formulas with missing 'Upload Repository'.  But those formulas are also not getting imported.

![image](https://user-images.githubusercontent.com/49313548/107973706-90a22b00-6fdb-11eb-8562-57ca90578e43.png)
	
		
The same issue exists in  telemetry permanent profile setup also, due to the upload repository option.

**Comment by igor-kostrov** [comment]
The issue were fixed in commit 009eb30 that is part of #34 pull request.

**Comment by ajayan508** [comment]
Verified the issue in latest build and the issue is resolved
